version: "3.9"
services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python superNova_2177.py"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build: ./transcendental-resonance-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8080:8080"
    depends_on:
      - backend
