name: Base Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/transcendental_resonance_frontend/src
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ inputs.python-version }}-
      - name: Check patch compliance
        if: github.event_name == 'pull_request'
        run: |
          python scripts/check_disclaimers.py origin/${{ github.event.pull_request.base.ref }}
      - name: Install dependencies with fallback mirror
        run: |
          python -m pip install --upgrade pip
          # Ensure Streamlit is present for smoke tests
          pip install streamlit
          if pip install -r requirements-minimal.txt -r requirements-dev.txt --index-url=https://pypi.org/simple; then
            echo "[INFO] Pip install succeeded using https://pypi.org/simple"
          else
            echo "[WARNING] Falling back to mirror: https://mirrors.aliyun.com/pypi/simple/"
            if pip install -r requirements-minimal.txt -r requirements-dev.txt --index-url=https://mirrors.aliyun.com/pypi/simple/; then
              echo "[INFO] Pip install succeeded using https://mirrors.aliyun.com/pypi/simple/"
            else
              echo "[ERROR] All pip index sources failed. Aborting."
              exit 1
            fi
          fi
          pip install -e .
      - run: mypy
      - run: pytest
      - name: Streamlit smoke test
        run: |
          streamlit run ui.py --server.headless true &
          for i in {1..30}; do
            if curl -f http://localhost:8501 >/dev/null 2>&1; then
              echo "Streamlit started after $i seconds"
              break
            fi
            sleep 1
          done
          if ! curl -f http://localhost:8501 >/dev/null 2>&1; then
            echo "Streamlit failed to start within timeout"
            pkill streamlit
            exit 1
          fi
          curl -f http://localhost:8501
          pkill streamlit
