# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[server]
headless = true
port = 8888
address = "0.0.0.0"
enableCORS = false

[theme]
base = "dark"
